name: shojin_app
description: "AtCoderの精進をスマホでも。"
homepage: https://github.com/tsukuba-denden/shojin_app

publish_to: 'none'

version: 0.6.4-Beta

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0
  path_provider: ^2.1.3
  pub_semver: ^2.1.4
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  archive: ^4.0.7
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0 # flutter_local_notifications の依存関係に合わせて修正

  # AtCoder問題のスクレイピングに必要なパッケージ
  http: ^1.5.0
  html: ^0.15.6
  flutter_markdown_plus: ^1.0.3
  flutter_code_editor: ^0.3.4
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  # 設定の保存に必要
  shared_preferences: ^2.2.3
  provider: ^6.1.5
  webview_flutter: ^4.7.0
  favicon: ^1.1.0
  share_plus: ^11.1.0
  open_file: ^3.5.10
  intl: ^0.20.2
  animations: ^2.0.11
  yaml: ^3.1.2
  # LaTeX/TeX数式レンダリング用
  flutter_math_fork: ^0.7.3
  android_package_installer:
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: main
  android_package_manager:
    git:
      url: https://github.com/ImranR98/android_package_manager
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  analyzer: ^8.1.1
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/twitter_logo.svg
    - assets/icon/youtube_logo.svg
    - assets/icon/github_logo.svg
  fonts:
    - family: HackGen
      fonts:
        - asset: assets/fonts/HackGen-Regular.ttf
          weight: 400
        - asset: assets/fonts/HackGen-Bold.ttf
          weight: 700
    - family: HackGen35
      fonts:
        - asset: assets/fonts/HackGen35-Regular.ttf
          weight: 400
        - asset: assets/fonts/HackGen35-Bold.ttf
          weight: 700
    - family: HackGenConsole
      fonts:
        - asset: assets/fonts/HackGenConsole-Regular.ttf
          weight: 400
        - asset: assets/fonts/HackGenConsole-Bold.ttf
          weight: 700
    - family: HackGen35Console
      fonts:
        - asset: assets/fonts/HackGen35Console-Regular.ttf
          weight: 400
        - asset: assets/fonts/HackGen35Console-Bold.ttf
          weight: 700
  

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

  adaptive_icon_foreground: "assets/icon/adaptive_foreground.png"
  adaptive_icon_background: "#261147"
  adaptive_icon_foreground_inset: 32